### ISSUE TITLE
A problem about ref in api document

### ISSUE THREAD

**Issue by 2239559319** [vuejs/composition-api-rfc#25]
![QQ截图20200425144054](https://user-images.githubusercontent.com/34960995/80273253-3447e500-8703-11ea-93ba-58cd772d9a18.png)

When I read compositon-api-rfc document in [website](https://vue-composition-api-rfc.netlify.app/api.html#template-refs), I found the code shown above. I don't know if this code is right. In my opinion, the code in the template should be
```html
<template>
  <div :ref="root"></div>
</template>
```
and it is my first contact with vue3, and i don't kown the correct code.

**Comment by ycmjason** [comment]
Looks like to me `ref="root"` is correct. But I agree, and I prefer `:ref` too but it doesn't make sense because in template refs are unwrapped. So `:ref="root"` will actually mean you are passing the value of `root` to `ref`.

**Comment by 2239559319** [comment]
> Looks like to me `ref="root"` is correct. But I agree, and I prefer `:ref` too but it doesn't make sense because in template refs are unwrapped. So `:ref="root"` will actually mean you are passing the value of `root` to `ref`.

thanks, i get it
