### ISSUE TITLE
Is there `beforeCreate` hook?

### ISSUE THREAD

**Issue by zgayjjf** [vuejs/composition-api-rfc#33]
`setup` function will be called `before the beforeCreate hook`.

[setup](https://github.com/vuejs/composition-api-rfc/blob/master/api.md#setup)

Is there still any `beforeCreate` hook? Or this is a misspelling for `beforeMount`?

![image](https://user-images.githubusercontent.com/24718872/82565501-1f992880-9bad-11ea-9832-83ff297e8a74.png)
![image](https://user-images.githubusercontent.com/24718872/82565528-2a53bd80-9bad-11ea-9e1b-6604658b8500.png)

**Comment by yyx990803** [comment]
The `beforeCreate` hook is still available via the Options API. There is just no equivalent `onBeforeCreate` method in the Composition API because you can just use `setup` for the same purpose.

**Comment by zgayjjf** [comment]
I see, there better be a detailed explanation for this. Otherwise, it may make others think there is still a `beforeCreate` lifecycle in Composition API. 😄
